# Import the math module so you can use some mathematical functions.

import math

# Choose any number between 0 and 360 and assign it to a variable angle_degrees.


angle_degrees = 45

# Use an appropriate function from the math module to convert the degrees value into radians.
# Store the result in a variable theta (also written as θ,
#     but you can't name a variable that!). Print out the value of theta.


theta = math.radians(angle_degrees)
print(theta)


# Use a function from the math module to calculate the tangent of theta, and print out the result.
# You do not need to make a separate variable.


print(math.tan(theta))

# Calculate tan(θ+π). You can get a value of pi as a variable from the math module.
# Print your result, and visually confirm that it's the same as
# tanθ that you calculated above (though there may be some "precision" errors)


print(math.tan(theta+math.pi))

# Import just the random() function from the random module.
# Note that you don't include the () when importing by name!


from random import random

# Call the random() function twice, printing out the results each time.
# You can run this cell multiple times to demonstrate that the ouput does in fact appear to be (pseudo)random.


print(random())
print(random())

# Import and use an appropriate function from the random module to generate a random integer between 3 and 18 (inclusive).
# Print the random number. Again, you can run this cell multiple times to see how it's random.


from random import randint
print(randint(3, 18))
print(randint(3, 18))

# Import the seed() function from the random module.
# This function sets the "seed" value used to generate random numbers.
# Random numbers are generated by taking a seed value and then performing mathematical transformations to it to produce the "random" number.
# The resulting value is then used as the "seed" for the next random number generated, allowing sequences of "pseudorandom" numbers to be produced. See here for details.
# The seed value is normally taken from "noisy" values (such as based on the computer's clock), but the seed() function allows you to effectively specify "which sequence" of random numbers will be produced.


from random import seed

# Use the seed() function to set the seed value to be 511, then call random() again twice (printing the results).
# Then call seed() a second time, again setting the seed value to be 511, and call and print random() twice more.
# Visually confirm that the sequences are the same.


seed(511)
print(random())
print(random())
seed(511)
print(random())
print(random())

# Bonus: in this cell, set theta to be a random number between 0 and 2π (check for a method that will let you pick from a uniform distribution of numbers).
# Then re-run the above cells that calculated its tangent. Do the trigonometric identities still hold?

from random import uniform
theta = uniform(0, 2*math.pi)
print(math.tan(theta))